#!/bin/sh
# Reproducible vips CLI commands for the convolution oracle capture.
# Run from the 'convolution' directory (paths are relative to it).
set -e

# kernel: sharp.mat
cat > fixtures/kernels/sharp.mat << 'EOF'
3 3 8 0
-1 -1 -1
-1 16 -1
-1 -1 -1
EOF

# kernel: blur.mat
cat > fixtures/kernels/blur.mat << 'EOF'
3 3 9 0
1 1 1
1 1 1
1 1 1
EOF

# kernel: line.mat
cat > fixtures/kernels/line.mat << 'EOF'
3 3 1 0
1 1 1
-2 -2 -2
1 1 1
EOF

# kernel: sobelk.mat
cat > fixtures/kernels/sobelk.mat << 'EOF'
3 3 1 0
1 2 1
0 0 0
-1 -2 -1
EOF

# kernel: box5.mat
cat > fixtures/kernels/box5.mat << 'EOF'
5 5 25 0
1 1 1 1 1
1 1 1 1 1
1 1 1 1 1
1 1 1 1 1
1 1 1 1 1
EOF

# kernel: asym.mat
cat > fixtures/kernels/asym.mat << 'EOF'
3 2 4 10
1 2 3
-1 0 1
EOF

# kernel: box5_1d.mat
cat > fixtures/kernels/box5_1d.mat << 'EOF'
5 1 5 0
1 1 1 1 1
EOF

# fixture: colour_test.ppm (synthetic mask_ideal pattern, generated by capture.py)
vips copy fixtures/colour_test.ppm fixtures/colour.v
vips extract_band fixtures/colour.v fixtures/mono.v 1
vips black fixtures/impulse_black.v 21 21
vips copy fixtures/impulse_black.v fixtures/impulse_mono.v
vips draw_rect fixtures/impulse_mono.v 255 10 10 1 1
vips copy '$REF_IMAGES/sample.jpg' fixtures/sample_colour.v
vips extract_band fixtures/sample_colour.v fixtures/sample_mono.v 1
# fixture: noise_mono.pgm (deterministic PRNG seed=42, generated by capture.py)
vips copy fixtures/noise_mono.pgm fixtures/noise_mono.v
# fixture: noise_colour.ppm (deterministic PRNG seed=43, generated by capture.py)
vips copy fixtures/noise_colour.ppm fixtures/noise_colour.v

# --- conv: impulse response (reveals each kernel exactly) ---
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_sharp_integer__vector.v fixtures/kernels/sharp.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_sharp_integer.v fixtures/kernels/sharp.mat --precision integer
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_sharp_float__vector.v fixtures/kernels/sharp.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_sharp_float.v fixtures/kernels/sharp.mat --precision float
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_blur_integer__vector.v fixtures/kernels/blur.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_blur_integer.v fixtures/kernels/blur.mat --precision integer
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_blur_float__vector.v fixtures/kernels/blur.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_blur_float.v fixtures/kernels/blur.mat --precision float
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_line_integer__vector.v fixtures/kernels/line.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_line_integer.v fixtures/kernels/line.mat --precision integer
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_line_float__vector.v fixtures/kernels/line.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_line_float.v fixtures/kernels/line.mat --precision float
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_sobelk_integer__vector.v fixtures/kernels/sobelk.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_sobelk_integer.v fixtures/kernels/sobelk.mat --precision integer
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_sobelk_float__vector.v fixtures/kernels/sobelk.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_sobelk_float.v fixtures/kernels/sobelk.mat --precision float
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_box5_integer__vector.v fixtures/kernels/box5.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_box5_integer.v fixtures/kernels/box5.mat --precision integer
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_box5_float__vector.v fixtures/kernels/box5.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_box5_float.v fixtures/kernels/box5.mat --precision float
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_asym_integer__vector.v fixtures/kernels/asym.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_asym_integer.v fixtures/kernels/asym.mat --precision integer
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_asym_float__vector.v fixtures/kernels/asym.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_asym_float.v fixtures/kernels/asym.mat --precision float
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_box5_1d_integer__vector.v fixtures/kernels/box5_1d.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_box5_1d_integer.v fixtures/kernels/box5_1d.mat --precision integer
vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_box5_1d_float__vector.v fixtures/kernels/box5_1d.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/impulse_mono.v fixtures/outputs/conv_impulse_box5_1d_float.v fixtures/kernels/box5_1d.mat --precision float

# --- conv: on make_test_colour fixture (matches ported test_conv probes) ---
vips conv fixtures/mono.v fixtures/outputs/conv_mono_sharp_integer__vector.v fixtures/kernels/sharp.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/conv_mono_sharp_integer.v fixtures/kernels/sharp.mat --precision integer
vips conv fixtures/mono.v fixtures/outputs/conv_mono_sharp_float__vector.v fixtures/kernels/sharp.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/conv_mono_sharp_float.v fixtures/kernels/sharp.mat --precision float
vips conv fixtures/mono.v fixtures/outputs/conv_mono_blur_integer__vector.v fixtures/kernels/blur.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/conv_mono_blur_integer.v fixtures/kernels/blur.mat --precision integer
vips conv fixtures/mono.v fixtures/outputs/conv_mono_blur_float__vector.v fixtures/kernels/blur.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/conv_mono_blur_float.v fixtures/kernels/blur.mat --precision float
vips conv fixtures/mono.v fixtures/outputs/conv_mono_line_integer__vector.v fixtures/kernels/line.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/conv_mono_line_integer.v fixtures/kernels/line.mat --precision integer
vips conv fixtures/mono.v fixtures/outputs/conv_mono_line_float__vector.v fixtures/kernels/line.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/conv_mono_line_float.v fixtures/kernels/line.mat --precision float
vips conv fixtures/mono.v fixtures/outputs/conv_mono_sobelk_integer__vector.v fixtures/kernels/sobelk.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/conv_mono_sobelk_integer.v fixtures/kernels/sobelk.mat --precision integer
vips conv fixtures/mono.v fixtures/outputs/conv_mono_sobelk_float__vector.v fixtures/kernels/sobelk.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/conv_mono_sobelk_float.v fixtures/kernels/sobelk.mat --precision float
vips conv fixtures/colour.v fixtures/outputs/conv_colour_sharp_integer__vector.v fixtures/kernels/sharp.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/conv_colour_sharp_integer.v fixtures/kernels/sharp.mat --precision integer
vips conv fixtures/colour.v fixtures/outputs/conv_colour_sharp_float__vector.v fixtures/kernels/sharp.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/conv_colour_sharp_float.v fixtures/kernels/sharp.mat --precision float
vips conv fixtures/colour.v fixtures/outputs/conv_colour_blur_integer__vector.v fixtures/kernels/blur.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/conv_colour_blur_integer.v fixtures/kernels/blur.mat --precision integer
vips conv fixtures/colour.v fixtures/outputs/conv_colour_blur_float__vector.v fixtures/kernels/blur.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/conv_colour_blur_float.v fixtures/kernels/blur.mat --precision float
vips conv fixtures/colour.v fixtures/outputs/conv_colour_line_integer__vector.v fixtures/kernels/line.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/conv_colour_line_integer.v fixtures/kernels/line.mat --precision integer
vips conv fixtures/colour.v fixtures/outputs/conv_colour_line_float__vector.v fixtures/kernels/line.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/conv_colour_line_float.v fixtures/kernels/line.mat --precision float
vips conv fixtures/colour.v fixtures/outputs/conv_colour_sobelk_integer__vector.v fixtures/kernels/sobelk.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/conv_colour_sobelk_integer.v fixtures/kernels/sobelk.mat --precision integer
vips conv fixtures/colour.v fixtures/outputs/conv_colour_sobelk_float__vector.v fixtures/kernels/sobelk.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/conv_colour_sobelk_float.v fixtures/kernels/sobelk.mat --precision float

# --- compass: impulse response (exact kernel-rotation reveal) ---
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t1_max_integer__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t1_max_integer.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision integer
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t1_max_float__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision float
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t1_max_float.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision float
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t1_sum_integer__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t1_sum_integer.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision integer
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t1_sum_float__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision float
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t1_sum_float.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision float
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t2_max_integer__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t2_max_integer.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision integer
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t2_max_float__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision float
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t2_max_float.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision float
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t2_sum_integer__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t2_sum_integer.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision integer
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t2_sum_float__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision float
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t2_sum_float.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision float
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t3_max_integer__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t3_max_integer.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision integer
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t3_max_float__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision float
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t3_max_float.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision float
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t3_sum_integer__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t3_sum_integer.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision integer
vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t3_sum_float__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision float
VIPS_NOVECTOR=1 vips compass fixtures/impulse_mono.v fixtures/outputs/compass_impulse_sharp_t3_sum_float.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision float

# --- compass: on ported test_compass inputs (sample.jpg mono/colour) ---
# NB: test_compass only asserts output dims == input dims (no numeric probe);
# we still capture avg + a probe point as a behavioral spot-check.
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t1_max_integer__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t1_max_integer.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision integer
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t1_max_float__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t1_max_float.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision float
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t1_sum_integer__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t1_sum_integer.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision integer
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t1_sum_float__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t1_sum_float.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision float
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t2_max_integer__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t2_max_integer.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision integer
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t2_max_float__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t2_max_float.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision float
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t2_sum_integer__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t2_sum_integer.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision integer
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t2_sum_float__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t2_sum_float.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision float
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t3_max_integer__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t3_max_integer.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision integer
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t3_max_float__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t3_max_float.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision float
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t3_sum_integer__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t3_sum_integer.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision integer
vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t3_sum_float__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_mono.v fixtures/outputs/compass_sample_mono_t3_sum_float.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision float
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t1_max_integer__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t1_max_integer.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision integer
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t1_max_float__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t1_max_float.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine max --precision float
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t1_sum_integer__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t1_sum_integer.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision integer
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t1_sum_float__vector.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t1_sum_float.v fixtures/kernels/sharp.mat --times 1 --angle d45 --combine sum --precision float
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t2_max_integer__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t2_max_integer.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision integer
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t2_max_float__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t2_max_float.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine max --precision float
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t2_sum_integer__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t2_sum_integer.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision integer
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t2_sum_float__vector.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t2_sum_float.v fixtures/kernels/sharp.mat --times 2 --angle d45 --combine sum --precision float
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t3_max_integer__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t3_max_integer.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision integer
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t3_max_float__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t3_max_float.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine max --precision float
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t3_sum_integer__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision integer
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t3_sum_integer.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision integer
vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t3_sum_float__vector.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision float
VIPS_NOVECTOR=1 vips compass fixtures/sample_colour.v fixtures/outputs/compass_sample_colour_t3_sum_float.v fixtures/kernels/sharp.mat --times 3 --angle d45 --combine sum --precision float

# --- convsep: gaussmat(sigma=2, min_ampl=0.1) 2D vs separable ---
vips gaussmat fixtures/kernels/gaussmat_sample_2d_integer.mat 2.0 0.1 --precision integer
vips gaussmat fixtures/kernels/gaussmat_sample_sep_integer.mat 2.0 0.1 --precision integer --separable
vips conv fixtures/sample_mono.v fixtures/outputs/convsep_mono_conv2d_integer__vector.v fixtures/kernels/gaussmat_sample_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/sample_mono.v fixtures/outputs/convsep_mono_conv2d_integer.v fixtures/kernels/gaussmat_sample_2d_integer.mat --precision integer
vips convsep fixtures/sample_mono.v fixtures/outputs/convsep_mono_convsep1d_integer__vector.v fixtures/kernels/gaussmat_sample_sep_integer.mat --precision integer
VIPS_NOVECTOR=1 vips convsep fixtures/sample_mono.v fixtures/outputs/convsep_mono_convsep1d_integer.v fixtures/kernels/gaussmat_sample_sep_integer.mat --precision integer
vips gaussmat fixtures/kernels/gaussmat_sample_2d_float.mat 2.0 0.1 --precision float
vips gaussmat fixtures/kernels/gaussmat_sample_sep_float.mat 2.0 0.1 --precision float --separable
vips conv fixtures/sample_mono.v fixtures/outputs/convsep_mono_conv2d_float__vector.v fixtures/kernels/gaussmat_sample_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/sample_mono.v fixtures/outputs/convsep_mono_conv2d_float.v fixtures/kernels/gaussmat_sample_2d_float.mat --precision float
vips convsep fixtures/sample_mono.v fixtures/outputs/convsep_mono_convsep1d_float__vector.v fixtures/kernels/gaussmat_sample_sep_float.mat --precision float
VIPS_NOVECTOR=1 vips convsep fixtures/sample_mono.v fixtures/outputs/convsep_mono_convsep1d_float.v fixtures/kernels/gaussmat_sample_sep_float.mat --precision float
vips gaussmat fixtures/kernels/gaussmat_sample_2d_integer.mat 2.0 0.1 --precision integer
vips gaussmat fixtures/kernels/gaussmat_sample_sep_integer.mat 2.0 0.1 --precision integer --separable
vips conv fixtures/sample_colour.v fixtures/outputs/convsep_colour_conv2d_integer__vector.v fixtures/kernels/gaussmat_sample_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/sample_colour.v fixtures/outputs/convsep_colour_conv2d_integer.v fixtures/kernels/gaussmat_sample_2d_integer.mat --precision integer
vips convsep fixtures/sample_colour.v fixtures/outputs/convsep_colour_convsep1d_integer__vector.v fixtures/kernels/gaussmat_sample_sep_integer.mat --precision integer
VIPS_NOVECTOR=1 vips convsep fixtures/sample_colour.v fixtures/outputs/convsep_colour_convsep1d_integer.v fixtures/kernels/gaussmat_sample_sep_integer.mat --precision integer
vips gaussmat fixtures/kernels/gaussmat_sample_2d_float.mat 2.0 0.1 --precision float
vips gaussmat fixtures/kernels/gaussmat_sample_sep_float.mat 2.0 0.1 --precision float --separable
vips conv fixtures/sample_colour.v fixtures/outputs/convsep_colour_conv2d_float__vector.v fixtures/kernels/gaussmat_sample_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/sample_colour.v fixtures/outputs/convsep_colour_conv2d_float.v fixtures/kernels/gaussmat_sample_2d_float.mat --precision float
vips convsep fixtures/sample_colour.v fixtures/outputs/convsep_colour_convsep1d_float__vector.v fixtures/kernels/gaussmat_sample_sep_float.mat --precision float
VIPS_NOVECTOR=1 vips convsep fixtures/sample_colour.v fixtures/outputs/convsep_colour_convsep1d_float.v fixtures/kernels/gaussmat_sample_sep_float.mat --precision float
vips gaussmat fixtures/kernels/gaussmat_synth_2d_integer.mat 2.0 0.1 --precision integer
vips gaussmat fixtures/kernels/gaussmat_synth_sep_integer.mat 2.0 0.1 --precision integer --separable
vips conv fixtures/mono.v fixtures/outputs/convsep_synthmono_conv2d_integer__vector.v fixtures/kernels/gaussmat_synth_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/convsep_synthmono_conv2d_integer.v fixtures/kernels/gaussmat_synth_2d_integer.mat --precision integer
vips convsep fixtures/mono.v fixtures/outputs/convsep_synthmono_convsep1d_integer__vector.v fixtures/kernels/gaussmat_synth_sep_integer.mat --precision integer
VIPS_NOVECTOR=1 vips convsep fixtures/mono.v fixtures/outputs/convsep_synthmono_convsep1d_integer.v fixtures/kernels/gaussmat_synth_sep_integer.mat --precision integer
vips gaussmat fixtures/kernels/gaussmat_synth_2d_float.mat 2.0 0.1 --precision float
vips gaussmat fixtures/kernels/gaussmat_synth_sep_float.mat 2.0 0.1 --precision float --separable
vips conv fixtures/mono.v fixtures/outputs/convsep_synthmono_conv2d_float__vector.v fixtures/kernels/gaussmat_synth_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/convsep_synthmono_conv2d_float.v fixtures/kernels/gaussmat_synth_2d_float.mat --precision float
vips convsep fixtures/mono.v fixtures/outputs/convsep_synthmono_convsep1d_float__vector.v fixtures/kernels/gaussmat_synth_sep_float.mat --precision float
VIPS_NOVECTOR=1 vips convsep fixtures/mono.v fixtures/outputs/convsep_synthmono_convsep1d_float.v fixtures/kernels/gaussmat_synth_sep_float.mat --precision float

# --- gaussblur: conv(gaussmat) vs gaussblur() on make_test_colour fixture ---
vips gaussmat fixtures/kernels/gaussmat_mono_integer_s1.0_2d_integer.mat 1.0 0.2 --precision integer
vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.0_conv__vector.v fixtures/kernels/gaussmat_mono_integer_s1.0_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.0_conv.v fixtures/kernels/gaussmat_mono_integer_s1.0_2d_integer.mat --precision integer
vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.0_direct__vector.v 1.0 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.0_direct.v 1.0 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_mono_integer_s1.2_2d_integer.mat 1.2 0.2 --precision integer
vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.2_conv__vector.v fixtures/kernels/gaussmat_mono_integer_s1.2_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.2_conv.v fixtures/kernels/gaussmat_mono_integer_s1.2_2d_integer.mat --precision integer
vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.2_direct__vector.v 1.2 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.2_direct.v 1.2 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_mono_integer_s1.4_2d_integer.mat 1.4 0.2 --precision integer
vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.4_conv__vector.v fixtures/kernels/gaussmat_mono_integer_s1.4_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.4_conv.v fixtures/kernels/gaussmat_mono_integer_s1.4_2d_integer.mat --precision integer
vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.4_direct__vector.v 1.4 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.4_direct.v 1.4 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_mono_integer_s1.6_2d_integer.mat 1.6 0.2 --precision integer
vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.6_conv__vector.v fixtures/kernels/gaussmat_mono_integer_s1.6_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.6_conv.v fixtures/kernels/gaussmat_mono_integer_s1.6_2d_integer.mat --precision integer
vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.6_direct__vector.v 1.6 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.6_direct.v 1.6 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_mono_integer_s1.8_2d_integer.mat 1.8 0.2 --precision integer
vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.8_conv__vector.v fixtures/kernels/gaussmat_mono_integer_s1.8_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.8_conv.v fixtures/kernels/gaussmat_mono_integer_s1.8_2d_integer.mat --precision integer
vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.8_direct__vector.v 1.8 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_integer_s1.8_direct.v 1.8 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_mono_float_s1.0_2d_float.mat 1.0 0.2 --precision float
vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.0_conv__vector.v fixtures/kernels/gaussmat_mono_float_s1.0_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.0_conv.v fixtures/kernels/gaussmat_mono_float_s1.0_2d_float.mat --precision float
vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.0_direct__vector.v 1.0 --min-ampl 0.2 --precision float
VIPS_NOVECTOR=1 vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.0_direct.v 1.0 --min-ampl 0.2 --precision float
vips gaussmat fixtures/kernels/gaussmat_mono_float_s1.2_2d_float.mat 1.2 0.2 --precision float
vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.2_conv__vector.v fixtures/kernels/gaussmat_mono_float_s1.2_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.2_conv.v fixtures/kernels/gaussmat_mono_float_s1.2_2d_float.mat --precision float
vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.2_direct__vector.v 1.2 --min-ampl 0.2 --precision float
VIPS_NOVECTOR=1 vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.2_direct.v 1.2 --min-ampl 0.2 --precision float
vips gaussmat fixtures/kernels/gaussmat_mono_float_s1.4_2d_float.mat 1.4 0.2 --precision float
vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.4_conv__vector.v fixtures/kernels/gaussmat_mono_float_s1.4_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.4_conv.v fixtures/kernels/gaussmat_mono_float_s1.4_2d_float.mat --precision float
vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.4_direct__vector.v 1.4 --min-ampl 0.2 --precision float
VIPS_NOVECTOR=1 vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.4_direct.v 1.4 --min-ampl 0.2 --precision float
vips gaussmat fixtures/kernels/gaussmat_mono_float_s1.6_2d_float.mat 1.6 0.2 --precision float
vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.6_conv__vector.v fixtures/kernels/gaussmat_mono_float_s1.6_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.6_conv.v fixtures/kernels/gaussmat_mono_float_s1.6_2d_float.mat --precision float
vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.6_direct__vector.v 1.6 --min-ampl 0.2 --precision float
VIPS_NOVECTOR=1 vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.6_direct.v 1.6 --min-ampl 0.2 --precision float
vips gaussmat fixtures/kernels/gaussmat_mono_float_s1.8_2d_float.mat 1.8 0.2 --precision float
vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.8_conv__vector.v fixtures/kernels/gaussmat_mono_float_s1.8_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.8_conv.v fixtures/kernels/gaussmat_mono_float_s1.8_2d_float.mat --precision float
vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.8_direct__vector.v 1.8 --min-ampl 0.2 --precision float
VIPS_NOVECTOR=1 vips gaussblur fixtures/mono.v fixtures/outputs/gaussblur_mono_float_s1.8_direct.v 1.8 --min-ampl 0.2 --precision float
vips gaussmat fixtures/kernels/gaussmat_colour_integer_s1.0_2d_integer.mat 1.0 0.2 --precision integer
vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.0_conv__vector.v fixtures/kernels/gaussmat_colour_integer_s1.0_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.0_conv.v fixtures/kernels/gaussmat_colour_integer_s1.0_2d_integer.mat --precision integer
vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.0_direct__vector.v 1.0 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.0_direct.v 1.0 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_colour_integer_s1.2_2d_integer.mat 1.2 0.2 --precision integer
vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.2_conv__vector.v fixtures/kernels/gaussmat_colour_integer_s1.2_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.2_conv.v fixtures/kernels/gaussmat_colour_integer_s1.2_2d_integer.mat --precision integer
vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.2_direct__vector.v 1.2 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.2_direct.v 1.2 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_colour_integer_s1.4_2d_integer.mat 1.4 0.2 --precision integer
vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.4_conv__vector.v fixtures/kernels/gaussmat_colour_integer_s1.4_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.4_conv.v fixtures/kernels/gaussmat_colour_integer_s1.4_2d_integer.mat --precision integer
vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.4_direct__vector.v 1.4 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.4_direct.v 1.4 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_colour_integer_s1.6_2d_integer.mat 1.6 0.2 --precision integer
vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.6_conv__vector.v fixtures/kernels/gaussmat_colour_integer_s1.6_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.6_conv.v fixtures/kernels/gaussmat_colour_integer_s1.6_2d_integer.mat --precision integer
vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.6_direct__vector.v 1.6 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.6_direct.v 1.6 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_colour_integer_s1.8_2d_integer.mat 1.8 0.2 --precision integer
vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.8_conv__vector.v fixtures/kernels/gaussmat_colour_integer_s1.8_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.8_conv.v fixtures/kernels/gaussmat_colour_integer_s1.8_2d_integer.mat --precision integer
vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.8_direct__vector.v 1.8 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_integer_s1.8_direct.v 1.8 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_colour_float_s1.0_2d_float.mat 1.0 0.2 --precision float
vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.0_conv__vector.v fixtures/kernels/gaussmat_colour_float_s1.0_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.0_conv.v fixtures/kernels/gaussmat_colour_float_s1.0_2d_float.mat --precision float
vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.0_direct__vector.v 1.0 --min-ampl 0.2 --precision float
VIPS_NOVECTOR=1 vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.0_direct.v 1.0 --min-ampl 0.2 --precision float
vips gaussmat fixtures/kernels/gaussmat_colour_float_s1.2_2d_float.mat 1.2 0.2 --precision float
vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.2_conv__vector.v fixtures/kernels/gaussmat_colour_float_s1.2_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.2_conv.v fixtures/kernels/gaussmat_colour_float_s1.2_2d_float.mat --precision float
vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.2_direct__vector.v 1.2 --min-ampl 0.2 --precision float
VIPS_NOVECTOR=1 vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.2_direct.v 1.2 --min-ampl 0.2 --precision float
vips gaussmat fixtures/kernels/gaussmat_colour_float_s1.4_2d_float.mat 1.4 0.2 --precision float
vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.4_conv__vector.v fixtures/kernels/gaussmat_colour_float_s1.4_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.4_conv.v fixtures/kernels/gaussmat_colour_float_s1.4_2d_float.mat --precision float
vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.4_direct__vector.v 1.4 --min-ampl 0.2 --precision float
VIPS_NOVECTOR=1 vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.4_direct.v 1.4 --min-ampl 0.2 --precision float
vips gaussmat fixtures/kernels/gaussmat_colour_float_s1.6_2d_float.mat 1.6 0.2 --precision float
vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.6_conv__vector.v fixtures/kernels/gaussmat_colour_float_s1.6_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.6_conv.v fixtures/kernels/gaussmat_colour_float_s1.6_2d_float.mat --precision float
vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.6_direct__vector.v 1.6 --min-ampl 0.2 --precision float
VIPS_NOVECTOR=1 vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.6_direct.v 1.6 --min-ampl 0.2 --precision float
vips gaussmat fixtures/kernels/gaussmat_colour_float_s1.8_2d_float.mat 1.8 0.2 --precision float
vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.8_conv__vector.v fixtures/kernels/gaussmat_colour_float_s1.8_2d_float.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.8_conv.v fixtures/kernels/gaussmat_colour_float_s1.8_2d_float.mat --precision float
vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.8_direct__vector.v 1.8 --min-ampl 0.2 --precision float
VIPS_NOVECTOR=1 vips gaussblur fixtures/colour.v fixtures/outputs/gaussblur_colour_float_s1.8_direct.v 1.8 --min-ampl 0.2 --precision float

# --- sharpen: unsharp mask on sample.jpg (matches ported test_sharpen) ---
vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s0.5_m1_2__vector.v --sigma 0.5 --m1 1 --m2 2
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s0.5_m1_2.v --sigma 0.5 --m1 1 --m2 2
vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s0.5_noop__vector.v --sigma 0.5 --m1 0 --m2 0
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s0.5_noop.v --sigma 0.5 --m1 0 --m2 0
vips subtract fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s0.5_noop.v fixtures/outputs/sharpen_mono_s0.5_diff.v.sub.v
vips abs fixtures/outputs/sharpen_mono_s0.5_diff.v.sub.v fixtures/outputs/sharpen_mono_s0.5_diff.v
vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s1.0_m1_2__vector.v --sigma 1.0 --m1 1 --m2 2
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s1.0_m1_2.v --sigma 1.0 --m1 1 --m2 2
vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s1.0_noop__vector.v --sigma 1.0 --m1 0 --m2 0
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s1.0_noop.v --sigma 1.0 --m1 0 --m2 0
vips subtract fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s1.0_noop.v fixtures/outputs/sharpen_mono_s1.0_diff.v.sub.v
vips abs fixtures/outputs/sharpen_mono_s1.0_diff.v.sub.v fixtures/outputs/sharpen_mono_s1.0_diff.v
vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s1.5_m1_2__vector.v --sigma 1.5 --m1 1 --m2 2
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s1.5_m1_2.v --sigma 1.5 --m1 1 --m2 2
vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s1.5_noop__vector.v --sigma 1.5 --m1 0 --m2 0
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s1.5_noop.v --sigma 1.5 --m1 0 --m2 0
vips subtract fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s1.5_noop.v fixtures/outputs/sharpen_mono_s1.5_diff.v.sub.v
vips abs fixtures/outputs/sharpen_mono_s1.5_diff.v.sub.v fixtures/outputs/sharpen_mono_s1.5_diff.v
vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s2.0_m1_2__vector.v --sigma 2.0 --m1 1 --m2 2
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s2.0_m1_2.v --sigma 2.0 --m1 1 --m2 2
vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s2.0_noop__vector.v --sigma 2.0 --m1 0 --m2 0
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s2.0_noop.v --sigma 2.0 --m1 0 --m2 0
vips subtract fixtures/sample_mono.v fixtures/outputs/sharpen_mono_s2.0_noop.v fixtures/outputs/sharpen_mono_s2.0_diff.v.sub.v
vips abs fixtures/outputs/sharpen_mono_s2.0_diff.v.sub.v fixtures/outputs/sharpen_mono_s2.0_diff.v
vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s0.5_m1_2__vector.v --sigma 0.5 --m1 1 --m2 2
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s0.5_m1_2.v --sigma 0.5 --m1 1 --m2 2
vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s0.5_noop__vector.v --sigma 0.5 --m1 0 --m2 0
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s0.5_noop.v --sigma 0.5 --m1 0 --m2 0
vips subtract fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s0.5_noop.v fixtures/outputs/sharpen_colour_s0.5_diff.v.sub.v
vips abs fixtures/outputs/sharpen_colour_s0.5_diff.v.sub.v fixtures/outputs/sharpen_colour_s0.5_diff.v
vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s1.0_m1_2__vector.v --sigma 1.0 --m1 1 --m2 2
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s1.0_m1_2.v --sigma 1.0 --m1 1 --m2 2
vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s1.0_noop__vector.v --sigma 1.0 --m1 0 --m2 0
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s1.0_noop.v --sigma 1.0 --m1 0 --m2 0
vips subtract fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s1.0_noop.v fixtures/outputs/sharpen_colour_s1.0_diff.v.sub.v
vips abs fixtures/outputs/sharpen_colour_s1.0_diff.v.sub.v fixtures/outputs/sharpen_colour_s1.0_diff.v
vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s1.5_m1_2__vector.v --sigma 1.5 --m1 1 --m2 2
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s1.5_m1_2.v --sigma 1.5 --m1 1 --m2 2
vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s1.5_noop__vector.v --sigma 1.5 --m1 0 --m2 0
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s1.5_noop.v --sigma 1.5 --m1 0 --m2 0
vips subtract fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s1.5_noop.v fixtures/outputs/sharpen_colour_s1.5_diff.v.sub.v
vips abs fixtures/outputs/sharpen_colour_s1.5_diff.v.sub.v fixtures/outputs/sharpen_colour_s1.5_diff.v
vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s2.0_m1_2__vector.v --sigma 2.0 --m1 1 --m2 2
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s2.0_m1_2.v --sigma 2.0 --m1 1 --m2 2
vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s2.0_noop__vector.v --sigma 2.0 --m1 0 --m2 0
VIPS_NOVECTOR=1 vips sharpen fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s2.0_noop.v --sigma 2.0 --m1 0 --m2 0
vips subtract fixtures/sample_colour.v fixtures/outputs/sharpen_colour_s2.0_noop.v fixtures/outputs/sharpen_colour_s2.0_diff.v.sub.v
vips abs fixtures/outputs/sharpen_colour_s2.0_diff.v.sub.v fixtures/outputs/sharpen_colour_s2.0_diff.v

# --- fastcor / spcor: template matching ---
vips extract_area fixtures/sample_mono.v fixtures/outputs/sample_mono_template.v 20 45 10 10
vips fastcor fixtures/sample_mono.v fixtures/outputs/sample_mono_template.v fixtures/outputs/sample_mono_fastcor.v
vips spcor fixtures/sample_mono.v fixtures/outputs/sample_mono_template.v fixtures/outputs/sample_mono_spcor.v
vips extract_area fixtures/sample_colour.v fixtures/outputs/sample_colour_template.v 20 45 10 10
vips fastcor fixtures/sample_colour.v fixtures/outputs/sample_colour_template.v fixtures/outputs/sample_colour_fastcor.v
vips spcor fixtures/sample_colour.v fixtures/outputs/sample_colour_template.v fixtures/outputs/sample_colour_spcor.v
vips extract_area fixtures/noise_mono.v fixtures/outputs/noise_mono_template.v 20 20 10 10
vips fastcor fixtures/noise_mono.v fixtures/outputs/noise_mono_template.v fixtures/outputs/noise_mono_fastcor.v
vips spcor fixtures/noise_mono.v fixtures/outputs/noise_mono_template.v fixtures/outputs/noise_mono_spcor.v
vips extract_area fixtures/noise_colour.v fixtures/outputs/noise_colour_template.v 20 20 10 10
vips fastcor fixtures/noise_colour.v fixtures/outputs/noise_colour_template.v fixtures/outputs/noise_colour_fastcor.v
vips spcor fixtures/noise_colour.v fixtures/outputs/noise_colour_template.v fixtures/outputs/noise_colour_spcor.v

# --- supplementary: convasep / sobel / canny (not exercised by the current port) ---
vips convasep fixtures/impulse_mono.v fixtures/outputs/convasep_impulse_box5_1d__vector.v fixtures/kernels/box5_1d.mat
VIPS_NOVECTOR=1 vips convasep fixtures/impulse_mono.v fixtures/outputs/convasep_impulse_box5_1d.v fixtures/kernels/box5_1d.mat
vips convasep fixtures/sample_mono.v fixtures/outputs/convasep_sample_mono_box5_1d__vector.v fixtures/kernels/box5_1d.mat
VIPS_NOVECTOR=1 vips convasep fixtures/sample_mono.v fixtures/outputs/convasep_sample_mono_box5_1d.v fixtures/kernels/box5_1d.mat
vips convasep fixtures/sample_colour.v fixtures/outputs/convasep_sample_colour_box5_1d__vector.v fixtures/kernels/box5_1d.mat
VIPS_NOVECTOR=1 vips convasep fixtures/sample_colour.v fixtures/outputs/convasep_sample_colour_box5_1d.v fixtures/kernels/box5_1d.mat
vips sobel fixtures/impulse_mono.v fixtures/outputs/sobel_impulse__vector.v
VIPS_NOVECTOR=1 vips sobel fixtures/impulse_mono.v fixtures/outputs/sobel_impulse.v
vips sobel fixtures/sample_mono.v fixtures/outputs/sobel_sample_mono__vector.v
VIPS_NOVECTOR=1 vips sobel fixtures/sample_mono.v fixtures/outputs/sobel_sample_mono.v
vips sobel fixtures/sample_colour.v fixtures/outputs/sobel_sample_colour__vector.v
VIPS_NOVECTOR=1 vips sobel fixtures/sample_colour.v fixtures/outputs/sobel_sample_colour.v
vips canny fixtures/sample_mono.v fixtures/outputs/canny_mono_s1.4_integer__vector.v --sigma 1.4 --precision integer
VIPS_NOVECTOR=1 vips canny fixtures/sample_mono.v fixtures/outputs/canny_mono_s1.4_integer.v --sigma 1.4 --precision integer
vips canny fixtures/sample_mono.v fixtures/outputs/canny_mono_s1.4_float__vector.v --sigma 1.4 --precision float
VIPS_NOVECTOR=1 vips canny fixtures/sample_mono.v fixtures/outputs/canny_mono_s1.4_float.v --sigma 1.4 --precision float
vips canny fixtures/sample_colour.v fixtures/outputs/canny_colour_s1.4_integer__vector.v --sigma 1.4 --precision integer
VIPS_NOVECTOR=1 vips canny fixtures/sample_colour.v fixtures/outputs/canny_colour_s1.4_integer.v --sigma 1.4 --precision integer
vips canny fixtures/sample_colour.v fixtures/outputs/canny_colour_s1.4_float__vector.v --sigma 1.4 --precision float
VIPS_NOVECTOR=1 vips canny fixtures/sample_colour.v fixtures/outputs/canny_colour_s1.4_float.v --sigma 1.4 --precision float

# --- #558 discriminating fixtures: masks/sigmas chosen to SEPARATE ---
# --- libvips's two integer-convolution paths, not to agree with them ---
# fixture: boxsum1147.pgm (3x3, eight 127s around a 131; window sum 1147)
vips copy fixtures/boxsum1147.pgm fixtures/boxsum1147.v
vips conv fixtures/boxsum1147.v fixtures/outputs/discrim_boxsum1147_blur_integer__vector.v fixtures/kernels/blur.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/boxsum1147.v fixtures/outputs/discrim_boxsum1147_blur_integer.v fixtures/kernels/blur.mat --precision integer
vips gaussblur fixtures/noise_mono.v fixtures/outputs/discrim_gaussblur_noise_s0.8_integer__vector.v 0.8 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/noise_mono.v fixtures/outputs/discrim_gaussblur_noise_s0.8_integer.v 0.8 --min-ampl 0.2 --precision integer
# kernel: hostile.mat (3x3 scale 3; passes vips_convi_intize, breaks any tolerance)
# kernel: hostile.mat
cat > fixtures/kernels/hostile.mat << 'EOF'
3 3 3 0
45 -17 -25
-33 -15 -34
55 53 -26
EOF

vips conv fixtures/noise_mono.v fixtures/outputs/discrim_hostile_mask_noise_integer__vector.v fixtures/kernels/hostile.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/noise_mono.v fixtures/outputs/discrim_hostile_mask_noise_integer.v fixtures/kernels/hostile.mat --precision integer
vips sobel fixtures/noise_mono.v fixtures/outputs/discrim_sobel_noise_mono__vector.v
VIPS_NOVECTOR=1 vips sobel fixtures/noise_mono.v fixtures/outputs/discrim_sobel_noise_mono.v

# --- #558 regime boundaries: which of the two kernels libvips picks ---
# --- (re-run any of these with VIPS_INFO=1 to see the decision) ---
vips cast fixtures/noise_mono.v fixtures/noise_mono_ushort.v ushort
vips conv fixtures/noise_mono_ushort.v fixtures/outputs/regime_ushort_conv_blur__vector.v fixtures/kernels/blur.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/noise_mono_ushort.v fixtures/outputs/regime_ushort_conv_blur.v fixtures/kernels/blur.mat --precision integer
vips gaussblur fixtures/noise_mono_ushort.v fixtures/outputs/regime_ushort_gaussblur_s1.6__vector.v 1.6 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/noise_mono_ushort.v fixtures/outputs/regime_ushort_gaussblur_s1.6.v 1.6 --precision integer
vips gaussblur fixtures/noise_mono.v fixtures/outputs/regime_gaussblur_s0.5__vector.v 0.5 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/noise_mono.v fixtures/outputs/regime_gaussblur_s0.5.v 0.5 --min-ampl 0.2 --precision integer
vips gaussblur fixtures/noise_mono.v fixtures/outputs/regime_gaussblur_s0.6__vector.v 0.6 --min-ampl 0.2 --precision integer
VIPS_NOVECTOR=1 vips gaussblur fixtures/noise_mono.v fixtures/outputs/regime_gaussblur_s0.6.v 0.6 --min-ampl 0.2 --precision integer
vips gaussmat fixtures/kernels/gaussmat_regime_s0.5_2d_integer.mat 0.5 0.2 --precision integer
vips conv fixtures/noise_mono.v fixtures/outputs/regime_conv_gaussmat2d_s0.5__vector.v fixtures/kernels/gaussmat_regime_s0.5_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/noise_mono.v fixtures/outputs/regime_conv_gaussmat2d_s0.5.v fixtures/kernels/gaussmat_regime_s0.5_2d_integer.mat --precision integer
vips gaussmat fixtures/kernels/gaussmat_regime_s0.6_2d_integer.mat 0.6 0.2 --precision integer
vips conv fixtures/noise_mono.v fixtures/outputs/regime_conv_gaussmat2d_s0.6__vector.v fixtures/kernels/gaussmat_regime_s0.6_2d_integer.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/noise_mono.v fixtures/outputs/regime_conv_gaussmat2d_s0.6.v fixtures/kernels/gaussmat_regime_s0.6_2d_integer.mat --precision integer
vips conv fixtures/noise_mono.v fixtures/outputs/regime_scale1_sobelk__vector.v fixtures/kernels/sobelk.mat --precision integer
VIPS_NOVECTOR=1 vips conv fixtures/noise_mono.v fixtures/outputs/regime_scale1_sobelk.v fixtures/kernels/sobelk.mat --precision integer
vips conv fixtures/noise_mono.v fixtures/outputs/regime_float_hostile__vector.v fixtures/kernels/hostile.mat --precision float
VIPS_NOVECTOR=1 vips conv fixtures/noise_mono.v fixtures/outputs/regime_float_hostile.v fixtures/kernels/hostile.mat --precision float
vips sharpen fixtures/noise_mono.v fixtures/outputs/regime_sharpen_s1.6__vector.v --sigma 1.6 --m1 1 --m2 2
VIPS_NOVECTOR=1 vips sharpen fixtures/noise_mono.v fixtures/outputs/regime_sharpen_s1.6.v --sigma 1.6 --m1 1 --m2 2
